# Force dep to vendor dependencies needed for codegen
# For now, we must specify all subpackages required due to a limitation of dep
# See https://github.com/golang/dep/issues/1306
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/gengo/args",
]

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.1.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.16"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.3"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "10.0.0"

[[constraint]]
  name = "github.com/containership/cerebral"
  version = "0.3.0-alpha"

[[constraint]]
  name = "github.com/containership/csctl"
  revision = "e912989f8c93458dc0593a0941e80d5d752b5aa5"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.3"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    go-tests = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false
    go-tests = false
