# Force dep to vendor dependencies needed for codegen
# For now, we must specify all subpackages required due to a limitation of dep
# See https://github.com/golang/dep/issues/1306
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.1.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.16"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "github.com/containership/cerebral"
  revision = "7f872b1f0a3de48961a1e7aedbc6d7e629a69a27"

[prune]
  go-tests = true
  # Note that we can't do this due to the code generator packages required; see above
  #unused-packages = true
