apiVersion: v1
kind: Service
metadata:
    name: cloud-coordinator
    namespace: containership-core
    labels:
        containership.io/app: cloud-coordinator
        containership.io/managed: "true"
spec:
    ports:
    - port: 8000
    type: NodePort
    selector:
        containership.io/app: cloud-coordinator
        containership.io/managed: "true"
