apiVersion: v1
kind: Service
metadata:
    name: containership-coordinator
    namespace: containership-core
    labels:
        containership.io: managed
spec:
    ports:
    - port: 8000
    type: NodePort
    selector:
        app: containership-coordinator
