apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: users.containership.io
spec:
  group: containership.io
  # Version should match Containership Cloud API version
  version: v3
  scope: Namespaced
  names:
    kind: User
    plural: users
    shortNames:
    - usr
