apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: registries.containership.io
  labels:
    containership.io: managed
spec:
  group: containership.io
  # Version should match Containership Cloud API version
  version: v3
  scope: Namespaced
  names:
    kind: Registry
    plural: registries
    shortNames:
    - reg
