---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: containership-core
  name: containership-agent
  labels:
    app: containership-agent
    containership.io: managed
spec:
  selector:
    matchLabels:
      app: containership-agent
  template:
    metadata:
      labels:
        app: containership-agent
        name: cloud-agent
    spec:
      volumes:
        - name: containership-home
          hostPath:
              path: /etc/containership/home
        - name: containership-scripts
          hostPath:
              path: /etc/containership/scripts
      containers:
        - name: containership-agent
          envFrom:
            - configMapRef:
                name: containership-env-configmap
          image: containership/cloud-agent
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: containership-home
              mountPath: /etc/containership/home
            - name: containership-scripts
              mountPath: /etc/containership/scripts
          resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
