---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: containership-core
  name: containership-agent
  labels:
    app: containership-agent
    tier: cloud-synchronize
    version: v1
spec:
  template:
    metadata:
      labels:
        app: containership-agent
        name: cloud-agent
    spec:
      volumes:
        - name: code
          hostPath:
              path: /Users/.minikube-mounts/internal
        - name: containership-volume
          hostPath:
              path: /opt/containership
              type: DirectoryOrCreate
      containers:
        - name: containership-agent
          envFrom:
            - configMapRef:
                name: containership-env-configmap
          env:
            - name: NODE_PRIVATE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: agent:debug
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: containership-volume
              mountPath: /opt/containership
          resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
