---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: containership-core
  name: cloud-agent
  labels:
    containership.io/app: cloud-agent
    containership.io/managed: "true"
spec:
  selector:
    matchLabels:
      containership.io/app: cloud-agent
      containership.io/managed: "true"
  template:
    metadata:
      labels:
        name: cloud-agent
        containership.io/app: cloud-agent
        containership.io/managed: "true"
    spec:
      volumes:
        - name: containership-mount
          hostPath:
              path: /etc/containership
      containers:
        - name: cloud-agent
          envFrom:
            - configMapRef:
                name: containership-env-configmap
          image: containership/cloud-agent
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: containership-mount
              mountPath: /etc/containership
          resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
