---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: containership-core
  name: cloud-coordinator
  labels:
    containership.io/app: cloud-coordinator
    containership.io/managed: "true"
spec:
  selector:
    matchLabels:
      containership.io/app: cloud-coordinator
      containership.io/managed: "true"
  template:
    metadata:
      labels:
        name: cloud-coordinator
        containership.io/app: cloud-coordinator
        containership.io/managed: "true"
    spec:
      volumes:
        - name: plugins-volume
          emptyDir: {}
      containers:
        - name: cloud-coordinator
          envFrom:
            - configMapRef:
                name: containership-env-configmap
          image: containership/cloud-coordinator
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /plugins
              name: plugins-volume
