---
# Note: Only Kubernetes v1.8+ clusters supported
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: containership-core
  name: containership-coordinator
  labels:
    app: containership-coordinator
    tier: cloud-synchronize
    version: v1
spec:
  selector:
    matchLabels:
      app: containership-coordinator
  template:
    metadata:
      labels:
        app: containership-coordinator
        name: cloud-coordinator
    spec:
      volumes:
        - name: code
          hostPath:
              path: /Users/.minikube-mounts/internal
      containers:
        - name: containership-coordinator
          envFrom:
            - configMapRef:
                name: containership-env-configmap
          env:
            - name: NODE_PRIVATE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: coordinator:debug
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
