---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: containership-core
  name: containership-coordinator
  labels:
    app: containership-coordinator
    tier: cloud-synchronize
    version: v1
spec:
  template:
    metadata:
      labels:
        app: containership-coordinator
        name: cloud-coordinator
    spec:
      containers:
        - env:
            -
              name: CONTAINERSHIP_CLOUD_ENVIRONMENT
              value: "production"
            -
              name: CONTAINERSHIP_CLOUD_CLUSTER_API_KEY
              valueFrom:
                secretKeyRef:
                    name: containershipCloudClusterAPIKey
                    key: token
            -
              name: CONTAINERSHIP_CLOUD_ORGANIZATION_ID
              value: ""
            -
              name: CONTAINERSHIP_CLOUD_CLUSTER_ID
              value: ""
            -
              name: NODE_PRIVATE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            -
              name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: ashleyschuett/cloud-agent:debug
          command: ["/app/containership", "coordinator"]
          imagePullPolicy: Always
          name: containership-coordinator
          resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
