---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: containership-core
  name: containership-coordinator
  labels:
    app: containership-coordinator
    containership.io/managed: "true"
spec:
  selector:
    matchLabels:
      app: containership-coordinator
  template:
    metadata:
      labels:
        app: containership-coordinator
        name: cloud-coordinator
    spec:
      containers:
        - name: containership-coordinator
          envFrom:
            - configMapRef:
                name: containership-env-configmap
          image: containership/cloud-agent-coordinator
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
